### ISSUE TITLE
[BOJ_11054_가장 긴 바이토닉 부분 수열] 시간복잡도를 O(N * logN) 까지 줄일 수 있을까?

### ISSUE THREAD

**Issue by rlawnsdn** [SSAFTUDY/Algorithm_Java#12]
### 질문 내용
O(N^2)은 되는데 O(N * logN)은 아무리 생각해도 되는지 모르겠음...
가장 긴 증가하는 부분 수열이 O(N * logN) 이 되니깐 이것도 될 거 같기도 한데...

**Comment by Jung-hansu** [comment]
fbddc5c
이 코드가 이분탐색 쓴 O(NlogN) 풀이입니당
[참고자료](https://velog.io/@jeongbeom4693/JAVA-LIS-%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98)
