### ISSUE TITLE
[boj_16434_드래곤앤던전] 반례 테케 다 맞는데 어디가 틀렸는지 알려줄 사람?

### ISSUE THREAD

**Issue by kangCoder** [SSAFTUDY/Algorithm_Java#13]
### (본인이 이해하고 적용한) 문제 접근 방식

1. 이분탐색을 돌릴 시작과 끝: maxHp가 들어갈 수 있는 시작과 끝으로 설정 (1~N*1e6*1e6)
2. mid == 대상 MaxHp, mid로 모든 방을 다 돌 수 있는지 확인
3. 못돌면 값을 더 위로 올리고, 가능하면 아래로 내림

--

### 본인 코드 (커밋 링크)

e0a45d5

--

### 질문 내용

어디가 틀렸는지 알려줄 사람? 일단 접근 방식은 틀린게 없어보이는데,, 주어진 테케랑 질문 게시판의 반례도 다 통과함.
몬스터랑 싸우는 부분도 while 제거하고 수식으로 바꿨는데 틀려서 어디가 틀린지 모르겠군요.

**Comment by Jung-hansu** [comment]
진짜 왜틀림???
[이건](https://www.acmicpc.net/source/75240428) 정답코드에 있던건데 이거랑 로직 똑같고 심지어 얘는 mid 구할때 오버플로우 내는데도 통과..

**Comment by kangCoder** [comment]
curAtk long으로 바꾸니까 해결;;
