### ISSUE TITLE
[BOJ_2295_세 수의 합] 로직 한번만 봐주세요

### ISSUE THREAD

**Issue by kanghyukjun** [SSAFTUDY/Algorithm_Java#14]
### (본인이 이해하고 적용한) 문제 접근 방식
1. 배열을 정렬 후 k를 가장 뒤에서부터 탐색한다.
2. x를 0번째 index, z를 k-1번째 index로 설정한다
3. y를 x와 z 사이의 값중 결정한다. y 값을 찾을 때 이진탐색을 사용한다.
4. 만약 arr[x]+arr[z]값이 arr[k]보다 크면 z값을 1 감소한다
5. y값을 찾을 수 있으면 arr[z]값을 출력 후 종료한다
6. y값을 찾지 못했으면 x를 1 증가시킨다 
--

### 본인 코드 (커밋 링크)
4c0e5f5
--

### 질문 내용
하나밖에 없는 테스트케이스도 맞고,
혹시 몰라서 백준 질문게시판에 있는 중복 경우 포함된 예제들도 돌려봤을 때 맞는데
어느 곳에서 틀리는지 모르겠습니다 도와주세요

**Comment by Jung-hansu** [comment]
```
int x = 0;
int z = k - 1;
...
```
이렇게 그냥 선언하면 안되고
```
for (int z = k - 1; z >= 0; z--){
    int x = 0;
    ...
}
```
이걸로 감싸줘야 함!
while문을 다 돌고 나면 x = 0부터, z는 하나 작은 수 부터 돌아야 하기 때문.
그래서 
```
if (arr[x] + arr[z] >= arr[k]) {
    z--;
    continue;
}
```
이 부분도 
```
if (arr[x] + arr[z] >= arr[k]) {
    break;
}
```
이렇게 해줘도 됨!
