### ISSUE TITLE
[BOJ_1068_트리] 어디서 틀렸을까?  DFS에서 틀린거 같은데

### ISSUE THREAD

**Issue by youngseonseo** [SSAFTUDY/Algorithm_Java#2]
### (본인이 이해하고 적용한) 문제 접근 방식
 ArrayList + DFS
ArrayList의 각 인덱스 숫자를 부모로 가지고 있는 리스트들끼리 묶는다.
ex) -1 0 0 1 1이면
[[1, 2],
[3, 4],
[0],
[0],
[0],
]
dfs 를 이용해 방문안한 자손 삭제

### 본인 코드 (커밋 링크)

0163e1f
--

### 질문 내용
예시 입출력은 동일하나 틀렸다고 나온다. 어디서 틀렸는지 모르겠다

**Comment by Jung-hansu** [comment]
지금 루트가 무조건 0인걸로 가정하고 있어서
루트가 2여도 0번노드 지우면 0이 출력되는중
```
77 if (remove == 0) { // 삭제 노드가 0이면 루트 노드만 남으므로
78	System.out.println(0);
79 }
```
이부분 remove==0이 아니라 루트노드가 들어가야 할 듯!

**Comment by youngseonseo** [comment]
이걸 놓쳤네
감사합니다아!
