### ISSUE TITLE
[BOJ_1949_우수마을] 메모리 초과 이슈...

### ISSUE THREAD

**Issue by DDongYul** [SSAFTUDY/Algorithm_Java#3]
### (본인이 이해하고 적용한) 문제 접근 방식
1. input을 받을 때, 번호가 작은 정점을 부모로 둠.
2. 노드 배열 만들어서 부모, 자식관계 연결하여 트리 구현
3. 트리의 리프노드를 찾아서 dp 시작
4. dp[n][0] 은 n번 정점이 우수 마을이 아닐때 -> 자식의 우수마을 여부 상관없으므로 모든 자식에 대하여 dp[child][0], dp[child][1] 중 큰 값을 더해줌
5. dp[n][1]은 n번 정점이 우수 마을일 때 이므로 자식은 모두 우수마을이 아니어야함 -> 모든 자식에 대하여 dp[child][0] 더해줌
6. 리프노드 부터 4,5번 과정 진행하고, 해당 정점 탐색을 끝내면 정점의 부모를 queue 끝에 넣어줌, queue에서 값 하나씩 꺼내가면서 진행하는데, 이 때 자식이 탐색이 끝나지 않은 경우가 있을 수 있음-> 검사를 통해 자식이 모두 탐색되지 않았으면 4,5번 진행하지 않고 다시 queue의 끝에 넣어줌.
7. queue에 더 이상 값이 없으면 종료 
--

### 본인 코드 (커밋 링크)

-- c8e5d4b

### 질문 내용
채점해보면 80퍼까지 가는 걸 봐서 아이디어는 맞은 것 같은데 메모리 초과가 뜹니다 ㅠㅠ 어디서 메모리 초과가 뜨는걸까요..?

**Comment by Jung-hansu** [comment]
# [땅땅땅]
```
51 if(a>b) {	//마을 번호가 작은 마을을 부모로 두기 위한 과정 
52 	int temp = a;
53	a = b;
54	b = temp;
55 }
```
아래 반례의 경우 4는 2와 3 모두의 자식이 되지만, 4의 부모는 3만 설정돼서
무한 루프에 빠짐
스택 버퍼 오버플로우로 인한 메모리 초과로 판명
```
2 4
3 4
```
