### ISSUE TITLE
[BOJ_22856_트리순회] 왜 틀림??

### ISSUE THREAD

**Issue by youngseonseo** [SSAFTUDY/Algorithm_Java#4]
### (본인이 이해하고 적용한) 문제 접근 방식
이차열 배열로 트리 구현

### 본인 코드 (커밋 링크)

6d831c2

### 질문 내용
휴우 왼쪽 노드랑 오른쪽 노드 다르게 처리해야하나요??

**Comment by kanghyukjun** [comment]
유사 중위 순회 종료 조건이 중위 순회를 했을 때 끝나는 노드를 방문했을 때여서 그렇습니다!

**Comment by kangCoder** [comment]
총 탐색에 들어간 간선의 수를 구하는 것과 순회가 끝났을 때의 노드를 구하는 것을 분리해서 생각하면 좋을듯?
