### ISSUE TITLE
[BOJ_22856_트리순회] dfs를 한 번만 돌리는 방법?

### ISSUE THREAD

**Issue by kangCoder** [SSAFTUDY/Algorithm_Java#5]
### (본인이 이해하고 적용한) 문제 접근 방식

1. 첫 번째 dfs에서 마지막에 방문하는 노드 찾고
2. 두 번째 dfs에서 방문 카운트하다가 마지막 방문 노드 찾으면 종료

---

### 본인 코드 (커밋 링크)

c942cf8fa768501eeb00c39823412b9a8a07dc5f

---

### 질문 내용

dfs를 한 번만 돌려서 마지막 방문 노드를 찾으면서 카운트하는 방법은 없으려나요

**Comment by Jung-hansu** [comment]
몇개의 노드를 방문했는지를 세는 cnt변수를 놓고
```
dfs(){
   ...
    dfs(왼쪽자식)
    <<카운팅 및 종료조건>>
    dfs(오른쪽자식)
    ...
}
```
이런 식으로 짜면 할거 하다가 중위순회 기준 마지막 방문 노드때 종료 조건 충족돼서 나가집니당

[제 코드](https://github.com/SSAFTUDY/Algorithm_Java/blob/main/hansu/week2/boj_22856_%ED%8A%B8%EB%A6%AC%EC%88%9C%ED%9A%8C.java)의 pseudoInorderCircuit() 참고!
