### ISSUE TITLE
[BOJ_20955_민서의응급수술] 이거 union-find 말고 다른 방법으로 푸는 방법?

### ISSUE THREAD

**Issue by kangCoder** [SSAFTUDY/Algorithm_Java#6]
### (본인이 이해하고 적용한) 문제 접근 방식

입력으로 들어오는 시냅스가 연결되어 있다 -> 끊기

각각의 조상을 셌을 때 자기자신인 경우를 센다 -> 트리에 들어와있지 않은 경우임

최종적으로 연산은
이미 연결되어 있는 뉴런들 + (뉴런 그룹의 수 - 1)

---

### 본인 코드 (커밋 링크)

ed827d9

---

### 질문 내용

이거 유파 말고 다르게 풀 방법은 없으려나

**Comment by kangCoder** [comment]
노드가 N개인 트리의 간선의 수는 N-1개니까 그거 이용해서 BFS 돌리면 되려나?

**Comment by DDongYul** [comment]
나는 유파 안쓰고 그룹 개수 셀 때 BFS 돌려서 그룹의 개수 셌음
1. BFS를 통해 집단의 개수 카운트
2. 집단들을 모두 이어줌 -> 실제로 이어주는건 아니고 간선을 (그룹 개수 -1)개 추가
3. 간선이 N-1개 초과하면 cycle이 발생하니까 끊어서 N-1개로 줄여줌
모두 직접 잇거나 줄이진 않고 개수만 카운트
