### ISSUE TITLE
[BOJ_1753_최단경로] Dijkstra 알고리즘 구현하기

### ISSUE THREAD

**Issue by kanghyukjun** [SSAFTUDY/Algorithm_Java#7]
### (본인이 이해하고 적용한) 문제 접근 방식
다익스트라 알고리즘을 구현해보려고 했는데 실패함 ㅜㅜ
틀린 접근 방식 : 
1. 우선순위 큐를 사용
2. 시작 노드의 모든 간선을 우선순위 큐에 넣음
3. 우선순위 큐에서 간선을 하나씩 빼면서 거리를 업데이트
4. 만약 큐에서 뺀 간선의 도착 노드가 처음 방문하는 곳이면 도착 노드에서 시작되는 모든 간선을 큐에 넣고 거리를 업데이트
5. 처음 방문하는 곳이 아니면 기존에 저장되었던 거리와 새로 계산된 거리를 비교 후 업데이트
6. 큐가 빌 때까지 3번 ~ 5번 과정을 반복
--

### 본인 코드 (커밋 링크)
성공한 코드 : 003e2a9
실패한 코드 : 6e5124a
--

### 질문 내용
제 접근 방식으로 Dijkstra 알고리즘을 구현하면 어떤 오류가 생기는지 궁금합니다 도와주세요...

성공한 코드에서는 반복문에서 현재 노드에서부터 갈 수 있는 모든 간선들의 거리를 확인하고 우선순위 큐에 넣기 때문에 Dijkstra 알고리즘 동작 과정이랑 동일하게 반복문을 빠져나간 후 que에서 제일 처음 뺀 노드가 이미 선택되지 않은 거리 중 가장 작은 거리를 가진 노드가 되는건가요
으악 너무 헷갈리네

**Comment by Jung-hansu** [comment]
내 생각에는
```
while N번 반복:
    1. 시작 지점과 가장 가까운 노드 fix;
    2. fix한 노드 주변의 노드 거리 업데이트;
```
한 사이클마다 출발지점이랑 "가장 가까운" 노드들을 선택해가는게 핵심인데,
보면 틀린 코드는 간선의 코스트만을 비교해서 업데이트하고, 맞은 코드는 업데이트했을 때의
노드의 값을 비교하고 나서 진행하고있음!
그래서 그렇지 않을까..?싶음
